//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpz4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegisterEntities : DbContext
    {
        public RegisterEntities()
            : base("name=RegisterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<notary> notarys { get; set; }
        public DbSet<person> persons { get; set; }
        public DbSet<poa> poas { get; set; }
        public DbSet<subject> subjects { get; set; }
        public DbSet<suspention> suspentions { get; set; }
    }
}
