//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpz4
{
    using System;
    using System.Collections.Generic;
    
    public partial class suspention
    {
        public suspention()
        {
            this.poas = new HashSet<poa>();
        }
    
        public int idSuspention { get; set; }
        public string NameOfDocument { get; set; }
        public int idNotary { get; set; }
        public int idPerson { get; set; }
        public System.DateTime DateOfDocument { get; set; }
    
        public virtual notary notary { get; set; }
        public virtual person person { get; set; }
        public virtual ICollection<poa> poas { get; set; }
    }
}
